#include "Constants.h"

const std::vector<std::string> Constants::lossMsgs = {
    "Well, that sucks.",
    "umadbro?",
    "How far did you get?",
    "OOPS.",
    "Did you just die?",
    "Maybe come back later?",
    "Well then.",
    "Welp.",
    "Maybe try playing on a larger screen?",
    "Did you even play through the tutorial?",
    "CRAP.",
    "Are you mad yet?",
    "If you played more \"accurately\" then maybe you would have won.",
    "Maybe a game like Geometry Dash would be more your speed.",
    "Did your hand slip?",
    "Did you have enough room to move your mouse?",
    "You should try playing this on a touchpad.",
    "Sometimes the winning move is not to play.",
    "Did you have fun at least?",
    "Better luck next time, eh?",
    "Have you considered being good at the game?",
    "How can you be this bad? Just use your mouse and get to the exit.",
    "Bad.",
    "You win! Oh wait, no you didn't.",
    "That's weird. You were moving just a few seconds ago.",
    "It was due to a bug, right?",
    "Skill issue.",
    "You lost because you didn't try hard enough.",
    "Practice makes perfect.",
    "I was able to beat this level on the first try. Unlike you.",
    "Don't worry. There's always next time. Always.",
    "Did you win yet?",
    "That was just a practice run, I'm sure.",
    "Wow. You are really bad at this.",
    "You lost ONLY because it touched JUST the tip of the thingy, I'm guessing.",
    "U wot m8?",
    "*raspberry noise*",
    "Are you dumb?",
    "Are you blind?",
    "That's rough.",
    "Ouch.",
    "Woooooooooooow.",
    "You really blew that one.",
    "...",
    "It's just a game after all.",
    "Were you AFK? How did you die to THAT?",
    "Whoops.",
    "Uh oh.",
    "Umm... have you considered getting better at the game?",
    "You were just warming up, right?",
    "How did you lose?",
    "Boo.",
    "Rookie mistake.",
    "Beginner's (bad) luck.",
    "Oh... you almost had it!",
    "Baby want his bottle?",
    "You were going way too fast there.",
    "You weren't going fast enough that time.",
    "I think you may have just lost.",
    "See the red? That's what you have to avoid.",
    "I don't think you should've touched that.",
    "Good game.",
    "Aw, screw it.",
    "Woah, what happened to your health?",
    "Um, are you okay?",
    "Looks like that didn't work out.",
    "Maybe you'll get it next time.",
    "Oooooh, that was a bad one.",
    "Steady... Steady...",
    "Slow and steady wins the race.",
    "At this rate, you'll be here forever.",
    "Even I'm getting bored at this point.",
    "Give me a break.",
    "Good grief.",
    "You can do better than that.",
    "Don't let it get to you.",
    "I'm sure you'll make it one day.",
    "I believed in you. Believed.",
    "Yes. Feel the burn...",
    "You: *smashes mouse*",
    "Just calm down and try again.",
    "Oh boy.",
    "Woah.",
    "Wow. Just wow.",
    "What happened there?",
    "Maybe don't hug *that* wall.",
    "We all have to start somewhere.",
    "You're not going for the world record, are you?",
    "Think you may have been going too fast that time?",
    "Maybe next time.",
    "You do plan on winning eventually, right?",
    "This level isn't even that hard.",
    "LOL!",
    "Don't give up. At least not yet.",
    "Really?",
    "Seriously?",
    "Ugh. Seriously?",
    "O RLY?",
    "All you had to do was not touch that.",
    "Pfffft.",
    "Ha, ha!",
    "Nope.",
    "Maybe, in time, you'll become an expert at this game. Just like me.",
    "Patience is key.",
    "At least you learned something new.",
    "Mindset is everything.",
    "Amazing things happen when you try.",
    "All of your hard work will pay off in time.",
    "That looked like it hurt.",
    "What's your IQ? 5?",
    "Dude."
};